name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore "Pacman _V2.sln"
      
    - name: Build
      run: dotnet build "Pacman _V2.sln" --no-restore -c Release
      
    - name: Test
      run: dotnet test "Pacman _V2.sln" --no-build --verbosity normal
      
    - name: Docker Build
      run: docker build -t "pacman" .

      # Aanpassingen vanaf week 4
    - name: Generate Code Coverage Report
      run: |
            dotnet test "Pacman _V2.sln" --no-build --verbosity normal --collect:"XPlat Code Coverage" --settings coverlet.runsettings
  
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: tests/TestResults

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build and Push Docker Image
      run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/sl2b-devops:latest .
          docker push ghcr.io/${{ github.repository_owner }}/sl2b-devops:latest

  security-scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Build Docker Image
        run: docker build -t pacman .
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'Pacman _V2:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'